version: '3.8'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  # Add this block for Grafana:
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
     
   